project_id = "rjajxabpndmpcgssymxw"

[functions.vat-calculator]
verify_jwt = false

[functions.vat-reconciliation]
verify_jwt = false

[functions.invoice-processor]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.income-tax-calculator]
verify_jwt = false
